project_name: faulty-crane
builds:
  - id: faulty-crane
    main: ./cli/faulty-crane/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
changelog:
  use: github-native
