project_name: faulty-creane
builds:
  - id: faulty-creane
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
changelog:
  use: github-native
