name: Initialize
description: Checks out repo and installs deps

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.18.2"

    - name: Install dependencies
      shell: bash
      run: |
        go get ./...
        go get -u golang.org/x/lint/golint
        export PATH="${PATH}:$(dirname $(go list -f {{.Target}} golang.org/x/lint/golint))"
