name: Initialize
description: Checks out repo and installs deps

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17.6"

    - name: Install dependencies
      run: |
        go get ./...
        go get -u golang.org/x/lint/golint
