name: Initialize

on: workflow_call

jobs:
  checkout_and_deps:
    timeout-minutes: 30
    name: Initialize and install deps
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"

      - name: Install dependencies
        run: |
          go get ./...
          go get -u golang.org/x/lint/golint
