name: Unit Test

on: workflow_call

jobs:
  unittest:
    timeout-minutes: 30
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Run vet, lint and tests
        run: |
          go vet ./...
          golint ./...
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        name: Upload to Codecov
        with:
          files: ./coverage.out
          flags: unittests