name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: debug
        run: |
          pwd
          ls
          ls .github/actions/init
      - name: init
        uses: ./.github/actions/init
      - name: install deps
        uses: ./.github/actions/unit_test
