name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        uses: ./.github/actions/init
      - name: install deps
        uses: ./.github/actions/unit_test
