name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Init
        uses: ./.github/actions/init
      - name: Unit test
        uses: ./.github/actions/unit_test
  integration_test:
    name: Integration test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        registry: [dockerhub]
        include:
          - registry: dockerhub
            registry_url: ""
            registry_username: DOCKERHUB_USERNAME
            registry_password: DOCKERHUB_PASSWORD
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Init
        uses: ./.github/actions/init
      - name: Integration test ${{ matrix.registry }}
        uses: ./.github/actions/integration_test
        with:
          container_registry_url: ${{ matrix.registry_url }}
          container_registry_username: ${{ secrets[matrix.registry_username] }}
          container_registry_password: ${{ secrets[matrix.registry_password] }}
