name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  init:
    name: Init
    uses: hytromo/faulty-crane/.github/workflows/_init.yml@master
  unit_test:
    needs: [init]
    name: Unit test
    uses: hytromo/faulty-crane/.github/workflows/_unit_test.yml@master
