name: Build Workflow

on: push

jobs:
  ci:
    timeout-minutes: 30
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: |
          go build cli/faulty-crane/*.go

      - name: Run vet, lint and tests
        run: |
          go vet ./...
          golint ./...
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        name: Upload to Codecov
        with:
          files: ./coverage.out
          flags: unittests # optional
